### ISSUE TITLE
Will the laser_speckle_filter look at outliers and give them value equal to their neighbours?

### ISSUE THREAD

**Issue by pooraniravindhiran** [ros-perception/laser_filters#100]

**Comment by pooraniravindhiran** [comment]
Need some clear documentation on that. Not able to follow with the params

**Comment by jonbinney** [comment]
From http://wiki.ros.org/laser_filters#LaserScanSpeckleFilter

"This filter removes outliers in a sensor_msgs/LaserScan. There are two filter methods that are available for this filter. These points are "removed" by setting the corresponding range value to NaN.: "

Does that answer your question?

**Comment by jonbinney** [comment]
(it doesn't set them to the value of their neighbors, it sets them to NaN.)
