### ISSUE TITLE
ROS 2 Release

### ISSUE THREAD

**Issue by DLu** [ros-perception/laser_filters#132]
Looks like there's been a lot of good work on the `ros2` branch. Has it been bloomed to the build farm yet? Particularly looking for a galactic release.

**Comment by jonbinney** [comment]
Hasn't been released to galactic or rolling yet - let me try it out on those distros to make sure it compiles;  then I'll release.

**Comment by jonbinney** [comment]
Oh I remember now.... I switched CI over to use the filters package from source, because the released version of that package had an issue. Let me try reverting the CI change and make sure CI passes.

**Comment by jonbinney** [comment]
Reverted the CI change here: https://github.com/ros-perception/laser_filters/pull/133

If that passes, I'll merge it and then do releases.

**Comment by jonbinney** [comment]
I made a release into rolling: https://github.com/ros/rosdistro/pull/30981

I had to create a new release repo and new track, so I'm going to wait until that PR gets merged into rosdistro before doing the galactic release.

**Comment by jonbinney** [comment]
Second attempt: https://github.com/ros/rosdistro/pull/30982

**Comment by jonbinney** [comment]
Looks like the rolling release succeeded this time: https://build.ros2.org/job/Rdev__laser_filters__ubuntu_focal_amd64/2/

**Comment by jonbinney** [comment]
Released version 2.0.1 into galactic: https://github.com/ros/rosdistro/pull/31007

I'll close this issue once it builds successfully.

**Comment by jonbinney** [comment]
Looks like it built: https://build.ros2.org/job/Gbin_uF64__laser_filters__ubuntu_focal_amd64__binary/

**Comment by DLu** [comment]
:tada:
