### ISSUE TITLE
ROS 2 Branch Missing Dependency on ament_cmake_auto

### ISSUE THREAD

**Issue by DLu** [ros-perception/laser_filters#134]
Causing failing build here: https://build.ros2.org/view/Rbin_uF64/job/Rbin_uF64__laser_filters__ubuntu_focal_amd64__binary/7/console

**Comment by jonbinney** [comment]
That's what I get for using desktop-full as the base docker image in CI... builds are super quick but i don't catch bugs like this. Fix incoming.

**Comment by jonbinney** [comment]
PR Here: https://github.com/ros-perception/laser_filters/pull/135

**Comment by jonbinney** [comment]
Fix merged, new rolling release created: https://github.com/ros/rosdistro/pull/31005

**Comment by DLu** [comment]
:+1:
