### ISSUE TITLE
laser_filters sources not in distribution.yaml for jade

### ISSUE THREAD

**Issue by tkruse** [ros-perception/laser_filters#26]
To reproduce:

```
$ rosinstall_generator desktop_full --rosdistro jade --deps --wet-only  --upstream-development
The following repositories with an unknown upstream will be ignored: driver_common, laser_filters, metapackages, rosbag_migration_rule, stage
```

Also see 
https://github.com/ros/filters/issues/11

**Comment by jonbinney** [comment]
Ah - looks like I missed something in the release. WIll fix this.

**Comment by jonbinney** [comment]
Re-released with source and doc info: https://github.com/ros/rosdistro/pull/9077

Will close this issue after that is merged and the fix is confirmed.

**Comment by jonbinney** [comment]
PR was merged; laser_filters now has source repo info in the distribution.yaml. @tkruse I re-ran the command you gave and it now finds laser_filters now. Should be all good.
