### ISSUE TITLE
Remove deprecated warning from footprint filter

### ISSUE THREAD

**Issue by stwirth** [ros-perception/laser_filters#29]
Although there might be a "newer" version of that filter in pr2_navigation_perception, this simple filter is still useful for circular shaped robots with off-centered lasers.

**Comment by jonbinney** [comment]
Agreed.  Want to submit a PR and I'll merge it?

**Comment by jonbinney** [comment]
Fixed by https://github.com/ros-perception/laser_filters/pull/43
