### ISSUE TITLE
Release please?

### ISSUE THREAD

**Issue by stwirth** [ros-perception/laser_filters#48]
@jonbinney could you run bloom please? Thanks!

**Comment by jonbinney** [comment]
Sure, I'll do a release today

**Comment by stwirth** [comment]
Thank you!

**Comment by jonbinney** [comment]
Forgot to do this yesterday. Done now:

Indigo: https://github.com/ros/rosdistro/pull/11590
Kinetic: https://github.com/ros/rosdistro/pull/11591
