### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-perception/laser_filters#64]
It looks like all of the dependencies for this package are available in Melodic, so it would be great to get this released.  Thanks in advance.

**Comment by jonbinney** [comment]
@clalancette I'll try and get to this tonight.

**Comment by jonbinney** [comment]
Argh, didn't finish. Will try again tomorrow. I want to build this first, but need to setup docker since I don't have an 18.04 machine handy.

**Comment by clalancette** [comment]
Great, thanks for taking a look.

Not sure if it helps at all, but I've been pretty happy using LXC to do my development on bionic: https://help.ubuntu.com/lts/serverguide/lxc.html .  You'd basically do:

```
sudo apt-get install lxc
sudo lxc-create -t download -n u1 -- --dist ubuntu --release bionic --arch amd64
```

And then you can get into the container with:

```
sudo lxc-attach -n u1
```

**Comment by jonbinney** [comment]
Got my container up and running, but didn't have time to test. Went ahead and released anyway; maybe we get lucky and the build works? If not I'll investigate further.

**Comment by jonbinney** [comment]
It built! Hooray!
