### ISSUE TITLE
Can't locate node laser_scan_filters

### ISSUE THREAD

**Issue by abylikhsanov** [ros-perception/laser_filters#66]
I want to filter the angles of the laser scans and wrote a launch file:
```
<launch>
  <node pkg="laser_filters" type="laser_scan_filters" output="screen" name="laser_scan">
    <rosparam command="load" file="$(find laser_filters)/launch/angle_filter.yaml" />
  </node>
</launch>
```

However, when I try to execute it, I get this error:
`ERROR: cannot launch node of type [laser_filters/laser_scan_filters]: can't locate node [laser_scan_filters] in package [laser_filters]`

Which is quite strange as there is a c++ executable in CMakeLists.

Any thoughts?

**Comment by jonbinney** [comment]
I'd suggest asking this on ROS answers - sounds like a problem with your catkin workspace or launchfile syntax, not with the code.
