### ISSUE TITLE
Citing this package

### ISSUE THREAD

**Issue by AabedSolayman** [ros-perception/laser_filters#98]
Hello,
I would like to know what is the best way to cite this package for academic purposes.
Thanky you

**Comment by jonbinney** [comment]
Hi @AabedSolayman - I don't think there is a publication associated with this package. Perhaps just include the website as in https://blog.apastyle.org/apastyle/2015/01/how-to-cite-software-in-apa-style.html

**Comment by AabedSolayman** [comment]
ok, thank you!
